AWSTemplateFormatVersion: 2010-09-09
Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            -
                Label:
                    default: 'Base de Datos Platzi-DynamoDB'
                Parameters:
                    - DynamoName
                    - DynamoKey
            -
                Label:
                    default: 'Funci贸n Lambda Platzi'
                Parameters:
                    - LambdaName
                    - LambdaRuntime
                    - LambdaBucket
                    - ZipName
        ParameterLabels:
            DynamoName:
                default: 'Ingrese el nombre de la tabla'
            DynamoKey:
                default: 'Ingrese el nombre de la Llave'
            LambdaName:
                default: 'Ingrese el nombre de la funci贸n lambda'
            LambdaRuntime:
                default: 'Seleccione el Runtimer de la funci贸n'
            LambdaBucket:
                default: 'Ingrese el nombre del bucket donde esta el c贸digo de la lambda'
            ZipName:
                default: 'Ingrese el nombre del .zip de la lambda'
Parameters:
    DynamoName:
        Description: Nombre
        Type: String
    DynamoKey:
        Description: Llave
        Type: String
    LambdaName:
        Description: Llave
        Type: String
    LambdaRuntime:
       Description: Runtime
       Type: String
       Default: python3.7
       AllowedValues:
            - python3.7
            - python2.7
            - ruby2.5
            - nodejs8.10
            - java8
            - dotnetcore2.1
    LambdaBucket:
        Description: Bucket
        Type: String
    ZipName:
        Description: Zip
        Type: String        
Resources:
    dynamo:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            TemplateURL: https://platzi-cloudformation.s3.us-east-2.amazonaws.com/dynamo.yml
            Parameters:
                DynamoName: !Ref DynamoName
                DynamoKey: !Ref DynamoKey
    api:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: lambda
        Properties:
            TemplateURL: https://platzi-cloudformation.s3.us-east-2.amazonaws.com/api.yml     
            Parameters:
                LambdaFunction: !GetAtt lambda.Outputs.LambdaFunction        
    lambda:
        Type: "AWS::CloudFormation::Stack"
        DependsOn: dynamo
        Properties:
            TemplateURL: https://platzi-cloudformation.s3.us-east-2.amazonaws.com/lambda.yml
            Parameters:
                LambdaName: !Ref LambdaName
                LambdaRuntime: !Ref LambdaRuntime
                LambdaBucket: !Ref LambdaBucket  
                ZipName: !Ref ZipName           
